<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        \DB::table('menus')->insert([
            [
                'name' => 'Japanese Kare Ramen',
                'price' => 36000,
                'description' => 'Ramen berkuah kental, kari Jepang kaya rempah, dipadukan dengan mie kenyal, potongan daging Ayam lembut, telur rebus setengah matang, serta Daun Bawang Segar, dengan Nori.',
                'image' => 'images/japanese_kare_ramen.jpeg',
                'category' => 'Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chiken Katsu Kare Rice',
                'price' => 34000,
                'description' => 'Chicken Katsu Kare Rice, ayam yang dimasak menggunakan bumbu kari Jepang, dengan potongan kentang dan wortel.',
                'image' => 'images/chicken_katsu_kare_rice.jpeg',
                'category' => 'Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tadaima Fried Rice',
                'price' => 36000,
                'description' => 'Tadaima Fried Rice, Nasi Goreng Khas Tadaima, berpadu dengan Chiken Katsu, Nori dan saus Teriyaki Ala Jepang dengan tambahan Andaliman.',
                'image' => 'images/tadaima_fried_rice.jpeg',
                'category' => 'Fried Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seafood Fried Rice',
                'price' => 35000,
                'description' => 'Seafood Fried Rice, disajikan dengan udang, fish cake, telur dan bakso ikan.',
                'image' => 'images/seafood_fried_rice.jpeg',
                'category' => 'Fried Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karegayaki Rice',
                'price' => 32000,
                'description' => 'Karegayaki Rice, ayam goreng tepung khas Jepang dengan saus teriyaki, irisan wortel, dan kaldu ayam.',
                'image' => 'images/karegayaki_rice.jpeg',
                'category' => 'Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken Fried Rice',
                'price' => 34000,
                'description' => 'Chicken Fried Rice, disajikan dengan potongan dada ayam yang lembut.',
                'image' => 'images/chicken_fried_rice.jpeg',
                'category' => 'Fried Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egg Fried Rice',
                'price' => 22000,
                'description' => 'Egg Fried Rice, Nasi goreng dengan irisan Nori dan telur.',
                'image' => 'images/egg_fried_rice.jpeg',
                'category' => 'Fried Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hokkaido Miso Ramen',
                'price' => 34000,
                'description' => 'Miso ramen menggunakan pasta kedelai fermentasi khas Jepang, chicken katsu, telur setengah matang, daun bawang dan nori.',
                'image' => 'images/hokkaido_miso_ramen.jpeg',
                'category' => 'Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kampung Style Fried Rice',
                'price' => 35000,
                'description' => 'Kampung Style Fried Rice, disajikan dengan ikan teri, telur, kangkung, petai, bumbu andaliman dan terasi.',
                'image' => 'images/kampung_style_fried_rice.jpeg',
                'category' => 'Fried Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karage Dry Ramen',
                'price' => 30000,
                'description' => 'Karage Dry Ramen disajikan dengan potongan Dada Ayam lembut dan gurih, telur mata sapi, Nori dan daun bawang.',
                'image' => 'images/karage_dry_ramen.jpeg',
                'category' => 'Dry Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kare Dry Ramen',
                'price' => 30000,
                'description' => 'Kare Dry Ramen disajikan dengan bumbu kari Jepang, telur mata sapi, Nori dan daun bawang.',
                'image' => 'images/kare_dry_ramen.jpeg',
                'category' => 'Dry Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Katsu Dry Ramen',
                'price' => 28000,
                'description' => 'Katsu Dry Ramen yang disajikan dengan toping Chicken Katsu, telur mata sapi, dan irisan Nori.',
                'image' => 'images/katsu_dry_ramen.jpeg',
                'category' => 'Dry Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seafood Kare Rice',
                'price' => 35000,
                'description' => 'Seafood Kare Rice, disajikan dengan udang, fish cake, telur dan bakso ikan.',
                'image' => 'images/seafood_kare_rice.jpeg',
                'category' => 'Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tadaima Chicken Rice',
                'price' => 36000,
                'description' => 'Tadaima Chicken Rice, disajikan dengan sayur sawi dan wortel, Chicken Katsu, perpaduan saus teriyaki dan andaliman beserta kaldu ayam.',
                'image' => 'images/tadaima_chicken_rice.jpeg',
                'category' => 'Rice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tori Paitan Ramen',
                'price' => 32000,
                'description' => 'Tori Paitan Ramen dengan kaldu ayam yang direbus selama 6 jam, chicken katsu, telur setengah matang, daun bawang dan nori.',
                'image' => 'images/tori_paitan_ramen.jpeg',
                'category' => 'Ramen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fried Mantao',
                'price' => 18000,
                'description' => 'Fried Mantao, roti kukus yang digoreng dan disajikan dengan saus gula merah.',
                'image' => 'images/fried_mantao.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'French fries',
                'price' => 16000,
                'description' => 'Kentang goreng klasik potongan stik yang garing di luar namun lembut di dalam, sempurna sebagai camilan pendamping.',
                'image' => 'images/french_fries.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prawn Tempura',
                'price' => 18000,
                'description' => 'Udang segar berbalut adonan tepung khas Jepang yang digoreng hingga renyah keemasan dan bertekstur ringan.',
                'image' => 'images/prawn_tempura.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '2 Scoop Vanilla Ice Cream',
                'price' => 12000,
                'description' => 'Dua bola es krim vanila bertekstur lembut dan dingin yang memberikan sensasi manis menyegarkan sebagai penutup hidangan.',
                'image' => 'images/2_scoop_vanilla_ice_cream.jpeg',
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fried Banana Choco Rice',
                'price' => 27000,
                'description' => 'Pisang Barangan Toba yang digoreng, ditambah parutan keju dan saus coklat yang ditaburi ceres.',
                'image' => 'images/fried_banana_choco_rice.jpeg',
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grill Banana Cheese',
                'price' => 27000,
                'description' => 'Grill banana cheese, Pisang Kepok yang dipanggang lalu ditaburi parutan keju dan ceres diatasnya.',
                'image' => 'images/grill_banana_cheese.jpeg',
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banana Split',
                'price' => 16000,
                'description' => 'Banana Split, perpaduan vanilla ice cream dan pisang barangan.',
                'image' => 'images/banana_split.jpeg',
                'category' => 'Dessert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sauted Broccoli',
                'price' => 22000,
                'description' => 'Broccoli segar yang ditumis, bertekstur renyah dan gurih.',
                'image' => 'images/sauted_broccoli.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karage',
                'price' => 24000,
                'description' => 'Karage, potongan daging ayam yang dibalut dengan tepung, digoreng hingga renyah, dengan saus teriyaki.',
                'image' => 'images/karage.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Broccoli Tempura',
                'price' => 18000,
                'description' => 'Broccoli Tempura, broccoli goreng yang dilapisi adonan tempura.',
                'image' => 'images/broccoli_tempura.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Onigiri',
                'price' => 22000,
                'description' => 'Nasi kepal Jepang klasik dengan isian daging ayam gurih dan saus mayones lembut, dibalut dengan lembaran nori yang renyah.',
                'image' => 'images/onigiri.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken Katsu',
                'price' => 24000,
                'description' => 'Fillet ayam empuk dengan balutan tepung roti yang digoreng hingga renyah keemasan, memberikan tekstur garing di luar dan tetap juicy di dalam.',
                'image' => 'images/chicken_katsu.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Onion Ring',
                'price' => 18000,
                'description' => 'Camilan renyah berupa irisan bawang bombay segar yang dibalut tepung bumbu krispi dan digoreng hingga matang sempurna dengan rasa gurih yang khas.',
                'image' => 'images/onion_ring.jpeg',
                'category' => 'Snacks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cappuccino',
                'price' => 20000,
                'description' => 'Kopi espresso kustom dengan susu steamed lembut dan sentuhan latte art cantik yang menghangatkan suasana.',
                'image' => 'images/cappuccino.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fresh Orange Juice',
                'price' => 18000,
                'description' => 'Sari jeruk murni pilihan yang diperas langsung tanpa tambahan pemanis buatan untuk rasa manis-asam alami yang sehat dan menyegarkan.',
                'image' => 'images/fresh_orange_juice.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iced Matcha Strawberry Latte',
                'price' => 28000,
                'description' => 'Perpaduan estetik matcha premium Jepang, susu segar, dan lapisan stroberi manis di bagian bawah yang menyegarkan mata dan lidah.',
                'image' => 'images/iced_matcha_strawberry_latte.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japanese Greentea',
                'price' => 10000,
                'description' => 'Teh hijau Jepang asli disajikan hangat yang menenangkan dan menjadi pendamping sempurna saat menikmati ramen.',
                'image' => 'images/japanese_greentea.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lemongrass Berry Fusion',
                'price' => 25000,
                'description' => 'Kesegaran ganda dari campuran beri manis dan aroma serai autentik dalam sajian dingin yang membangkitkan semangat.',
                'image' => 'images/lemongrass_berry_fusion.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matcha Creamy Shake',
                'price' => 30000,
                'description' => 'Smoothie kental dari bubuk matcha premium pilihan yang di-blend lembut untuk pencinta rasa teh hijau yang bold dan creamy.',
                'image' => 'images/matcha_creamy_shake.jpeg',
                'category' => 'Drinks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}